Initial version
vertx-howtos/graphql-howto pull request #1
Opened 2019-05-07 21:34 UTC by tsegismont

Closes https://github.com/vertx-howtos/vertx-howtos.github.io/issues/2

2019-05-09 07:07 UTC, jponge requested changes
Very good howto!

2019-05-09 07:07 UTC, jponge commented on README.adoc
> += Implementing a GraphQL server
Note: when you merge you will have to update https://github.com/vertx-howtos/vertx-howtos.github.io/blob/master/_data/howtos.yml

2019-05-09 07:07 UTC, jponge commented on README.adoc
> +* the `complete` _mutation_ that takes the task `id` as parameter and returns a _boolean_ indicating whether the operation was succesful
Typo: successful

2019-05-09 07:07 UTC, jponge commented on README.adoc
> +
For all query executions, I'd rather show the interaction with cURL or (better) HTTPie. As it is now we can click and see the result in the browser, but when reading the document the link between the query below and the execution may not be as obvious as if the URLs was in clear ;-)

2019-05-09 07:07 UTC, jponge commented on _config.yml
> +url: https://vertx-howtos.github.io/HOWTO-ID
graphql-howto

2019-05-09 12:44 UTC, tsegismont commented
>Very good howto!

I had a good teacher :bowing_man:

2019-05-10 12:37 UTC, jponge approved these changes
Go for it 🚀

2019-05-10 13:19 UTC, merged